### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by DGV1995** [Breta01/handwriting-ocr#100]
PackagesNotFoundError: The following packages are not available from current channels:

  - pyqt==5.9.2=py36h05f1152_2
  - matplotlib==3.0.1=py36h5429711_0
  - libxml2==2.9.8=h26e45fe_1
  - graphite2==1.3.12=h23475e2_2
  - freeglut==3.0.0=hf484d3e_5
  - bzip2==1.0.6=h14c3975_5
  - libedit==3.1.20170329=h6b74fdf_2
  - mkl_random==1.0.1=py36h4414c95_1
  - readline==7.0=h7b6447c_5
  - openssl==1.0.2p=h14c3975_0
  - harfbuzz==1.8.8=hffaf4a1_0
  - protobuf==3.6.1=py36he6710b0_0
  - etc...

**Comment by Breta01** [comment]
I will check that out. Try removing the "=py36h05f1152_2" parts.

**Comment by DGV1995** [comment]
Thanks! It works now :)
