### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 64, 58, 1) for Tensor 'inputs:0', which has shape '(?, ?, 2400)'

### ISSUE THREAD

**Issue by DGV1995** [Breta01/handwriting-ocr#101]
Hi Breta, while trying Recogition using CTC model, I get the next error: 'ValueError: Cannot feed value of shape (1, 64, 58, 1) for Tensor 'inputs:0', which has shape '(?, ?, 2400)'

I am using one of your pictures.

Thanks!

**Comment by Breta01** [comment]
This is because I still didn't update the uploaded models. Train the CTC model by yourself and then use it. That will solve the issue.

BTW did the suggestion from issue #100 work?

**Comment by DGV1995** [comment]
Yes, it worked, thanks!

I'll wait for the uploads :)

**Comment by mdumer** [comment]
Its uploaded or still have previous version?
I tried this thing today and get the same error. any other solution for it?

**Comment by Breta01** [comment]
I finally got the time and uploaded new version of the CTC model. Try downloading the models once again and replacing the old ones. It should work now.
