### ISSUE TITLE
'TrainingPlot' object has no attribute 'updateCost'

### ISSUE THREAD

**Issue by kaushik226** [Breta01/handwriting-ocr#102]
Hi breta
unable to train the word_classifier_ctc file following is the error iam getting
AttributeError                            Traceback (most recent call last)
<ipython-input-25-10df7e520331> in <module>
     23                 # Plotting loss
     24                 tmpLoss = loss.eval(fd)
---> 25                 trainPlot.updateCost(tmpLoss, i_batch // LOSS_ITER)
     26 
     27             if i_batch % TEST_ITER == 0:

AttributeError: 'TrainingPlot' object has no attribute 'updateCost'

**Comment by kaushik226** [comment]
naming issues i figured it out

thanks

**Comment by MuruganRAIdev** [comment]
@kaushik226  where we need to change the name here? i was changed TrainingPlot class updateCost --> updateloss but again facing same issue

**Comment by ashutoshkumara1** [comment]
I Have also Same Issue, What to Do Breta1 Suggest Me! After All You Father of this code?

**Comment by luffy078** [comment]
@kaushik226  at least leave your thread with a solution.

**Comment by mouni25** [comment]
Replace with
trainPlot.update_loss(tmpLoss, i_batch // LOSS_ITER)

**Comment by theEngineer47** [comment]
tmpLoss is not defined ??
