### ISSUE TITLE
ValueError: as_list() is not defined on an unknown TensorShape. in word_classifier_CTC.ipynb accuracy + padding cell

### ISSUE THREAD

**Issue by kaushik226** [Breta01/handwriting-ocr#103]
Hi Breta
when i try to run the accuracy + padding block in word_classifier_CTC.ipynb notebook following is the error iam getting i tried with different approach but still unable to solve it

dataset i used --- iam

ValueError                                Traceback (most recent call last)
<ipython-input-18-fcec18635b42> in <module>
      1 pred_length = decoded[0].get_shape().as_list()[1]
----> 2 targets_length = targets.get_shape().as_list()[1]
      3 
      4 pad_lenght = tf.maximum(pred_length, targets_length)
      5 

~/ocr_env/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py in as_list(self)
    902     """
    903     if self._dims is None:
--> 904       raise ValueError("as_list() is not defined on an unknown TensorShape.")
    905     return [dim.value for dim in self._dims]
    906 

ValueError: as_list() is not defined on an unknown TensorShape.

**Comment by Breta01** [comment]
There is reason why it was commented out, because it doesn't work. Use label error rate as performance indicator. I will update the code once I have some time.
