### ISSUE TITLE
Issue with importing page, words, characters from ocr

### ISSUE THREAD

**Issue by vamsime** [Breta01/handwriting-ocr#106]
Hi Breta,

Please help.

I am getting the following error: 
`OSError: File /handwriting-ocr/src/ocr/../../models/gap-clas/CNN-CG.meta does not exist.`

when I try the following code:
`from ocr import page, words, characters`

**Comment by Asus1996** [comment]
Hi can i know how to solve this problem

**Comment by shekarneo** [comment]
> Hi can i know how to solve this problem

what is the exact error, if you are facing cannot import page, words, characters error do this before importing `from ocr import page, words, characters`
`sys.path.append('path where ocr/words.py and page.py exists ')`

**Comment by dhea1323** [comment]
Please help. i still got the error

here's the code in .../notebook/OCR.ipynb
```python
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2

sys.path.append('/content/handwriting-ocr/src')
sys.path.append('/content/handwriting-ocr/src/ocr')

from ocr.normalization import word_normalization, letter_normalization
from ocr import page, words, characters
from ocr.helpers import implt, resize
from ocr.tfhelpers import Model
from ocr.datahelpers import idx2char
```

and here's the error,
```OSError: File /content/handwriting-ocr/src/ocr/../../models/gap-clas/CNN-CG.meta does not exist.```
