### ISSUE TITLE
Word_Classifier Not Loading Image

### ISSUE THREAD

**Issue by ashutoshkumara1** [Breta01/handwriting-ocr#114]
Loading words...
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-48-507315b83ff1> in <module>
----> 1 train_images, train_labels = load_words_data('data/sets/train.csv', is_csv=True)
         2 dev_images, dev_labels = load_words_data('data/sets/dev.csv', is_csv=True)

~HTR\src\ocr\datahelpers.py in load_words_data(dataloc, is_csv, load_gaplines)
          if is_csv:
--->        csv.field_size_limit(sys.maxsize)
              length = 0
              for loc in dataloc:

OverflowError: Python int too large to convert to C long

**Comment by 17sushmita** [comment]
> ## Loading words...
> OverflowError Traceback (most recent call last)
> in
> ----> 1 train_images, train_labels = load_words_data('data/sets/train.csv', is_csv=True)
> 2 dev_images, dev_labels = load_words_data('data/sets/dev.csv', is_csv=True)
> 
> ~HTR\src\ocr\datahelpers.py in load_words_data(dataloc, is_csv, load_gaplines)
> if is_csv:
> ---> csv.field_size_limit(sys.maxsize)
> length = 0
> for loc in dataloc:
> 
> OverflowError: Python int too large to convert to C long

did you solve this?

**Comment by Breta01** [comment]
This is duplicit with #142
