### ISSUE TITLE
Cambridge Handwriting Database Missing

### ISSUE THREAD

**Issue by vijnasu** [Breta01/handwriting-ocr#122]
ftp://svr-ftp.eng.cam.ac.uk/pub/data/handwriting_databases.README
ftp://svr-ftp.eng.cam.ac.uk/pub/data/
These links are broken. Can you suggest new ones?

**Comment by Breta01** [comment]
It works for me both in Firefox and Chrome. I also added code for automatic download to make the process easier. It will by added in following update: #125

**Comment by Rajeshwar21** [comment]
Yeah, Link is not working. Can u check it once

**Comment by Jayasreem05** [comment]
Yes, the link isn't working. Kindly check once.

**Comment by paboe** [comment]
The link isn't working. Please reopen the issue.

**Comment by rexionmars** [comment]
broken link

**Comment by mustafaemirhanyildiz** [comment]
These links are still not working
