### ISSUE TITLE
Issue running OCR (cannot find ../models/gap-clas/CNN-CG'))

### ISSUE THREAD

**Issue by dubbsbrandon** [Breta01/handwriting-ocr#123]
Running the OCR notebook and I cannot find this model. Is there something with either the dependencies or the actual location of where the model is being pulled from? The trace for the error goes back into Tensorflow. 

This is from the tfhelpers.py file:
22             saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)

Any help would be appreciated!

**Comment by JPremnath06** [comment]
The same issue i got. Did you solved this? ..Please share how you solved!!
