### ISSUE TITLE
Can i use your pre-trained models to recognise words in images with handwritten text? 

### ISSUE THREAD

**Issue by naveen-kumar-123** [Breta01/handwriting-ocr#129]
I haven been trying to extract word(s) from images with handwritten text in them. And i learned about this project. So, i now would like to know, if code in '..\notebooks\word_detection.ipynb' notebook to extract text from images?

**Comment by Breta01** [comment]
Hi,

you can use the code, but I am not sure if it will work as you expect. Right now it uses only computer vision algorithms with some heuristic to determine which regions are words and which aren't. It works decent if there is only text in the page, but it fails in many other cases.

If your pages contain some images, printed text, etc., then I would recommend using some machine learning approach for detecting the text. I am planning on adding such feature here too. If you want I can guide you how to do that, but I would expect contributing the code to this project.

**Comment by naveen-kumar-123** [comment]
Ok. If not that notebook, there are no notebooks or models in this repository that can detect text in images. 

I would really love to contribute, but honestly i don't have enough skill.

**Comment by Breta01** [comment]
Right, that is only notebook that does that. All models are for recognition of text (converting images to digital text).

Hopefully I will add this in near future, but I will close this issue for now.
