### ISSUE TITLE
How to train gap-class models?

### ISSUE THREAD

**Issue by PR-Iyyer** [Breta01/handwriting-ocr#14]
Hi,

Kindly help me with how to reproduce gap class models for my dataset. Its an emergency. I am stuck at this point.  I understood that pred values are taken from gaps. maybe since my char class -class model is not compatible with gap-class that am not able to separate characters properly. ???

**Comment by Breta01** [comment]
Hi,

I will maybe need a little bit clarification on your question.

Right now there are different approaches to recognition of handwritten text. One of them first separates a word into individual characters using Gap-Classifier and than recognize these separated characters using Char-Classifier. Therefore, Gap-Classifier and Char-Classifier are two different models. If you already have Char-Classifier which can recognize individual characters you need to train Gap-Classifier.

Gap-Classifier takes slices from an image of a word and classifies them on either letters or gaps. Right now I have two different Gap-Classifiers: [GapClassifier.ipynb](https://github.com/Breta01/handwriting-ocr/blob/master/GapClassifier.ipynb) and [GapClassifier-BiRNN.ipynb](https://github.com/Breta01/handwriting-ocr/blob/master/GapClassifier-BiRNN.ipynb). The first one uses only a convolutional neural network and the second uses it with a combination of a recurrent neural network.

The model you should train depends mainly on your dataset. The GapClassifier.ipynb takes as an input images separated into two classes: the images of letters are in 0 class and the images of gaps between letters have class 1. On the other hand, the GapClassifier-BiRNN.ipynb takes as an input images of words with an array of numbers corresponding to positions of gaps in the image.

Can you give me more details about your dataset, so I can give you more details.

**Comment by PR-Iyyer** [comment]
Thank you so much @Breta01 .  

I wanted the model to predict both lowercase and uppercase characters from even cursive written text. So I made handwritten charecter dataset (characters alone with corresponding labels) and trained it using CharClassifier.ipynb and obtained a model. This model only i used for test

**Comment by PR-Iyyer** [comment]
SO, can you please guide me with this.

**Comment by Breta01** [comment]
I understand the problem that we are facing here, but there is a limited number of things I can do about it.

The current GapClassifier which detects the borders between letters was trained on my handwriting and it fails on a handwriting of others. Therefore, if you want to improve the gap detection, you have to extend the current dataset and train new GapClassifier.

There is still a lot of work on this project. One of the most important parts is a large dataset, so I would really appreciate if you were willing to share your dataset.

Hope this explains the issue and thank you for your interest.

**Comment by PR-Iyyer** [comment]
Thanks @Breta01 .  This clarifies . Dataset will upload soon.
