### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by FadelMF** [Breta01/handwriting-ocr#140]
I have a problem 'AttributeError: module 'tensorflow' has no attribute 'Session', how I can fix this? I already installed tensorflow.

`AttributeError                            Traceback (most recent call last)
<ipython-input-21-1c5011de3819> in <module>
      8 sys.path.append('../src/')
      9 from ocr.normalization import word_normalization, letter_normalization
---> 10 from ocr import page, words, characters
     11 from ocr.helpers import implt, resize
     12 from ocr.tfhelpers import Model

D:\Master\handwriting-ocr-master\handwriting-ocr-master\src\ocr\characters.py in <module>
     14 location = os.path.dirname(os.path.abspath(__file__))
     15 CNN_model = Model(
---> 16     os.path.join(location, '../../models/gap-clas/CNN-CG'))
     17 CNN_slider = (60, 30)
     18 RNN_model = Model(

D:\Master\handwriting-ocr-master\handwriting-ocr-master\src\ocr\tfhelpers.py in __init__(self, loc, operation, input_name)
     18         self.input = input_name + ":0"
     19         self.graph = tf.Graph()
---> 20         self.sess = tf.Session(graph=self.graph)
     21         with self.graph.as_default():
     22             saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)

AttributeError: module 'tensorflow' has no attribute 'Session'
`
Thanks you

**Comment by Vibhugupta10616** [comment]
Hi I am also facing the same issue. If u were able to find a solution kindly post it.

**Comment by dhea1323** [comment]
Up! I have the same problem
