### ISSUE TITLE
No Function :  imageNorm ?

### ISSUE THREAD

**Issue by theEngineer47** [Breta01/handwriting-ocr#149]
Hi Breta,

I am working on your data labeling (words_labeling) but I can't find the function in ocr file...
Could you please help me about it ? 
thx!

ImportError  : cannot import name 'imageNorm' from 'ocr.normalization' (/Users/amed/Desktop/BRETA_DESKTOP_handwriting-ocr-master/src/ocr/normalization.py)

**Comment by Breta01** [comment]
Seems as old naming. Just rename it to `word_normalization`

**Comment by theEngineer47** [comment]
When I want to save the labeled images, I have button object "value" error. 
def save(self, b=None)... (b = None) and 

I do not have enough knowledge about GUI...

AttributeError: 'Button' object has no attribute 'value'
