### ISSUE TITLE
Tensor shape error / not training my images

### ISSUE THREAD

**Issue by theEngineer47** [Breta01/handwriting-ocr#151]
I have already create csv files and prepared the datasets files (dev, train,test, words...). Also I have trained the handwrite for 

I am training for word classifier by **wordclassifier-CTC-Retrain.ipynb** 

testimages = data/sets/test.csv, is_csv = True
trainimages = data/sets/train.csv , is_csv = True

Got problem on prediction:

Error:
----> 7         wordClass.run_op('train_step', fd, output=False)
...
...
...
---> 51             self.sess.run(
     52                 self.graph.get_operation_by_name(op),
     53                 feed_dict=feed)

ValueError: Cannot feed value of shape (18, 25, 3600) for Tensor 'inputs:0', which has shape '(None, 64, None, 1)'

**What is the problem? Could you please explain it for me?**

**Comment by DHANOLA** [comment]
hey can you tell me how did you solve this

Getting same error

![image](https://user-images.githubusercontent.com/55691616/197995080-8bbef6a8-7810-41bf-9eba-8c5118073a65.png)


![image](https://user-images.githubusercontent.com/55691616/197995087-1192650a-85cc-4a58-aa3b-a61dad0b997d.png)
