### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by PilliSiddharth** [Breta01/handwriting-ocr#154]
I'm using an WSL ubuntu environment, I have install the environment.yaml exactly like you have mentioned but I have no idea why I'm getting this error.

If there are any requirement issues please let me know. Please help me fix this error.

![image](https://user-images.githubusercontent.com/39644724/193413431-08954f13-c477-4ad3-b9ec-7cf4c4e3e8c1.png)

**Comment by ale90bsas** [comment]
Hi @PilliSiddharth,

I was able to solve this issue by following this post https://github.com/jasonlfunk/ocr-text-extraction/issues/5.
It seems like the implementation of cv2 has changed and it's now returning 3 values.
I had to modify files src/ocr/page.py and src/ocr/words.py

@Breta01, please let me know if you want me to send a PR on this.
Thanks for sharing this amazing project!

**Comment by PilliSiddharth** [comment]
Yeah thank you so much @ale90bsas it worked! had no idea previously why it was not working. It'd be great if you or me can raise a PR! 😀

**Comment by Breta01** [comment]
Hi @ale90bsas,
if you could create a PR with your changes, that would be awesome. I would highly appreciate it.
I am busy lately with university and I always thinking about fixing and improving this repo, but then I can't find the time to do it.

**Comment by ale90bsas** [comment]
Hi @Breta01, I'm not being able to create a branch in your project to submit a pull-request, can you help me with this? thanks

**Comment by Breta01** [comment]
@ale90bsas You have to first create the fork of the repo, then make changes on that, and then create the pull request. Check this video for reference: https://www.youtube.com/watch?v=nT8KGYVurIU
Please let me know if you need any further questions. I will be really happy if you manage to send the fixes

Thanks
