### ISSUE TITLE
No output for your own images also.

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#18]
Hello,

I have started using the charclassifier model.
I am running the OCR.ipynb and using the following image:  "data/textdet/2.jpg"
The output is very wierd. It cant detect any character.

**I think there is some thing wrong with the bounding boxes that we get after recalculating them as per the ratio**

Another error that I am getting is:

**IndexError                                Traceback (most recent call last)
<ipython-input-22-b57cdb9961eb> in <module>()
      1 # Crop image and get bounding boxes
----> 2 crop = page.detection(image)
      3 implt(crop)
      4 bBoxes = words.detection(crop)

~\handwriting-ocr-master-final\ocr\page.py in detection(image)
     17                                    np.ones((5, 11)))    
     18     # Countours
---> 19     pageContour = findPageContours(closedEdges, resize(image))
     20     # Recalculate to original scale
     21     pageContour = pageContour.dot(ratio(image))

~\handwriting-ocr-master-final\ocr\page.py in findPageContours(edges, img)
     94 
     95     # Sort corners and offset them
---> 96     pageContour = fourCornersSort(pageContour[:, 0])
     97     return contourOffset(pageContour, (-5, -5))
     98 

~\handwriting-ocr-master-final\ocr\page.py in fourCornersSort(pts)
     47 def fourCornersSort(pts):
     48     """ Sort corners: top-left, bot-left, bot-right, top-right"""
---> 49     diff = np.diff(pts, axis=1)
     50     summ = pts.sum(axis=1)
     51     return np.array([pts[np.argmin(summ)],

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\function_base.py in diff(a, n, axis)
   1922     slice1 = [slice(None)]*nd
   1923     slice2 = [slice(None)]*nd
-> 1924     slice1[axis] = slice(1, None)
   1925     slice2[axis] = slice(None, -1)
   1926     slice1 = tuple(slice1)

IndexError: list assignment index out of range**

This for the image: "data/textdet/1.jpg" and 3.jpg and many more.

Please help by checking it for yourself.

**Comment by Breta01** [comment]
Hi,
I fixed the issue in new commit. I also want to point out that in the folder `data/textdet/` the pages are already cropped; therefore, you can skip the `page.detection()` function.

**Comment by yasersakkaf** [comment]
Thanks Breta,

Now the output for your images is perfectly working.

However I am getting some issue with the following image.
![poss](https://user-images.githubusercontent.com/36536522/37582315-700bcdfc-2b72-11e8-9da5-2c58cb92cd5b.jpg)

I tried with and without `page.detection(image)` but it did not work.
Output is like this:

![image](https://user-images.githubusercontent.com/36536522/37582437-efa105aa-2b72-11e8-93f7-27ea8210b33d.png)


I think there is some problem with bounding boxes. The co-ordinates returned are not proper.
You can try it for yourself. I have sent you the image on your email too.
