### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Nayan-kumar-Chawda** [Breta01/handwriting-ocr#19]
![screenshot 33](https://user-images.githubusercontent.com/25155367/37634151-5f5d5cd8-2c1b-11e8-9436-0cffc88ec51e.png)

**Comment by Breta01** [comment]
Hi,
sorry for my slow response, I a bit busy right now. I will get to this during this week.
Hope you are not in hurry.

**Comment by Breta01** [comment]
I can't reproduce the issue. Could you give me more details? What version of numpy do you have?

**Comment by Nayan-kumar-Chawda** [comment]
Hi,
am sorry to for my delayed response, I have
 numpy 1.12.1

**Comment by Breta01** [comment]
I still can't reproduce the error. It looks like images or gaplines aren't loaded properly which cause the NoneType object error. Try downloading and running the project from scratch.
It the error persists, reopen this issue.

**Comment by haripranavk** [comment]
@Nayan-kumar-Chawda  were you able to solve this error?

**Comment by Breta01** [comment]
This issue is duplicate. Refer to #36
