### ISSUE TITLE
models/gap-clas/RNN/Bi-RNN-new.meta does not exist

### ISSUE THREAD

**Issue by splitbrain** [Breta01/handwriting-ocr#2]
I'm trying to get the OCR notebook to run, but get an error in the first cell:

``
OSError: File models/gap-clas/RNN/Bi-RNN-new.meta does not exist.
``
There are indeed no files with a `-new` prefix in that directory. Maybe you forgot to check in something?

**Comment by Breta01** [comment]
Thanks for pointing out the issue. I forgot to upload a new model.
I will solve it as soon as possible.
