### ISSUE TITLE
Error Continued...........

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#20]
Thanks Breta,

Now the output for your images is perfectly working.

However I am getting some issue with the following image.
![poss](https://user-images.githubusercontent.com/36536522/37582315-700bcdfc-2b72-11e8-9da5-2c58cb92cd5b.jpg)

I tried with and without `page.detection(image)` but it did not work.
Output is like this:

![image](https://user-images.githubusercontent.com/36536522/37582437-efa105aa-2b72-11e8-93f7-27ea8210b33d.png)

I think there is some problem with bounding boxes. The co-ordinates returned are not proper.
You can try it for yourself. I can send you the image on your email if you give it.

**Comment by Breta01** [comment]
Hi,

thanks for notifying me about the issue. I am aware of it. I am sorry, but I am a little bit busy right now. I will take a look at it as soon as possible.

**Comment by yasersakkaf** [comment]
Thanks in advance for your help.
 appreciate it.

**Comment by Breta01** [comment]
Hi,
I fixed the bug, it was error in rescaling of the bounding boxes.
Also I working on new future, so you can try running word detection like:
`bBoxes = words.detection(crop, join=True)`
This should join bounding box of word and dot above the 'i',

Hope it heps.

**Comment by yasersakkaf** [comment]
Thank you Breta.
I appreciate for all of your help till now. 
This is great.
