### ISSUE TITLE
Is training with IAM Dataset done?

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#22]
Hey there,
I wanted to know if the script for IAM is complete or not. If yes then will you kindly guide me how to use it.

**Comment by Breta01** [comment]
Hi,

I have not tested the training on the data produced by this script yet. The script should work if you provide a location of `words.txt` and `words/` folder from in IAM dataset. It should produce a new folder from which you should load images for training models.

One known issue of the script is slow image normalization function, which I would like to update soon. Otherwise, it should work fine.

**Comment by yasersakkaf** [comment]
There is words folder in the IAM dataset. However I don't think there is any words.txt file.

**Comment by yasersakkaf** [comment]
Thank you.
I will try it out and tell if any necessary changes are required or not.

**Comment by yasersakkaf** [comment]
The script worked fine. The normalized images are ready. Which classifier should I train using these Images.

**Comment by Breta01** [comment]
Try the WordClassifier-CTC.ipynb, just change the location in words loading function and it should work.

**Comment by yasersakkaf** [comment]
Thank you.
That would be for word classification. How do I train the Gap Classification model and Char Classification model using this Dataset

**Comment by Breta01** [comment]
If you have working word classification, you don't need gap + char classification. Gap + char classification is different approach to word recognition and you can't easily use IAM dataset for it. 

Plus in theory the CTC word classification should be better.

**Comment by yasersakkaf** [comment]
Thank you
I got it,

**Comment by souaissa** [comment]
Hi,
could you please tell me the requirement modification to use IAM daset

**Comment by Breta01** [comment]
@souaissa check the last comment in issue #49. I mentioned there required changes. I don't have much time, it would be great if somebody could make the pull request with that.
