### ISSUE TITLE
Chars_CZ, Chars_En undefined?

### ISSUE THREAD

**Issue by sagarhukkire** [Breta01/handwriting-ocr#26]
CHARS_CZ and chars_EN is undefined

**Comment by sagarhukkire** [comment]
CHARS_EN and CHARS_CZ need to define globally

**Comment by sagarhukkire** [comment]
i am wondering how you are accessing in datahelper file CHAR_EN and CHAR_CZ variables

**Comment by Breta01** [comment]
Ou, my bad. I merged them into one array. I will push fix for that.
