### ISSUE TITLE
ERROR with IAM dataset

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#27]
KeyError                                  Traceback (most recent call last)
<ipython-input-6-ba45a11d4556> in <module>()
     11 labels_idx = np.empty(len(labels), dtype=object)
     12 for i, label in enumerate(labels):
---> 13     labels_idx[i] = [char2idx(c) for c in label]    # char2idx(c, True)-2
     14 
     15 # Split data on train and test dataset

<ipython-input-6-ba45a11d4556> in <listcomp>(.0)
     11 labels_idx = np.empty(len(labels), dtype=object)
     12 for i, label in enumerate(labels):
---> 13     labels_idx[i] = [char2idx(c) for c in label]    # char2idx(c, True)-2
     14 
     15 # Split data on train and test dataset

~\handwriting-ocr-master\ocr\datahelpers.py in char2idx(c, sequence)
     30     if sequence:
     31         return chars_to_idx[c] + 1
---> 32     return chars_to_idx[c]
     33 
     34 def idx2char(idx, sequence=False):

KeyError: "'"

I think this error is because there is no single quote " ' " in the idx_to_char array or something

**Comment by Breta01** [comment]
Yes, that's true IAM dataset contains some characters, which aren't in my array of characters.
I quite busy right now, so I can't fix the issue. You can either skip those words or extend the array of characters.

**Comment by yasersakkaf** [comment]
I knew it ! 
Just wanted to confirm from you.
I will extend the Array.

Thanks for all the help upto now.
