### ISSUE TITLE
Bug of COLOR_BGR2RGB ?

### ISSUE THREAD

**Issue by flavienbwk** [Breta01/handwriting-ocr#32]
Hello,

I am trying to use your code that crops the image for scanned photos.

But here is what I get for output (knowing that the original image is a classic image with normal colors).
[https://i.imgur.com/8r1WWh6.png](https://i.imgur.com/8r1WWh6.png)

Have you an idea of what is the problem?

Thank you and have a great day.

**Comment by Breta01** [comment]
Can you share what code exactly produces this image (load and output function)? And what version of OpenCV do you have?
It might be strange, but OpenCV uses BGR as a default format for images.
