### ISSUE TITLE
Question about a function [question]

### ISSUE THREAD

**Issue by flavienbwk** [Breta01/handwriting-ocr#33]
Hello,

About resizing scanned documents, for this line : 
```
imageEdges = edgesDet(image, 200, 250, height)
```
Why have you chosen 200 and 250 ?

And here, why 5,5,5,5 ?
Inside:
```
img = cv2.copyMakeBorder(img, 5, 5, 5, 5, cv2.BORDER_CONSTANT, value=[0, 0, 0])
```

Thanks,

**Comment by Breta01** [comment]
For the first line:
`imageEdges = edgesDet(image, 200, 250, height)`
(not sure where you saw this height parameter), but the 200 and 250 are lower and higher threshold values for Canny Edge detector (read more about that).
The border have to be added to detect pages which aren't fully in the image and 5px works well.

**Comment by flavienbwk** [comment]
Thanks!

ps: The height parameter was added by myself.
