### ISSUE TITLE
unable to import  from ocr

### ISSUE THREAD

**Issue by raina99** [Breta01/handwriting-ocr#39]
On trying the code in ocr.ipynb
regarding the import  from ocr

```
from ocr.normalization import imageNorm, letterNorm
from ocr import page, words, charSeg
from ocr.helpers import implt, resize
from ocr.tfhelpers import Graph
from ocr.datahelpers import idx2char
```
It gives the error
OSError: File models/gap-clas/CNN-CG.meta does not exist.

**Comment by yasersakkaf** [comment]
Did you download the models and place them in the models folder?
I guess NO.
There are available from https://drive.google.com/file/d/1YbmsiJK3Wclfm6K8PrJuz-QROEKX1qis/view?usp=sharing

**Comment by raina99** [comment]
thanks @yasersakkaf  Your advice worked and helped a lot now its giving output . thanks a lot for taking your time to answering the issues.

 I wanted it to read capital handwritten text  and on giving  images of capital handwritten words
although it  draws bounding boxes for each character instead  of full word.

still on printing it is  giving very few correct .

@yasersakkaf 
can you suggest some way it can work for capital handwritten text .
I would appreciate that .
also it fails to print lower case words from my handwritting.

**Comment by yasersakkaf** [comment]
You are welcome.
If it is drawing boxes for each alphabet then your image must have lots of spaces between each character.
To make the ocr 100% working for your handwriting, you must train the model with your handwriting data else it wont give much accurate output.
The Question **How to train the model?** is already asked in the issues. You can search for it.
