### ISSUE TITLE
Tensorflow not found?

### ISSUE THREAD

**Issue by rochiey** [Breta01/handwriting-ocr#40]
When i try to click cell>run all in OCR.ipynb i got this error from cell 1

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-fd9caaa4c04f> in <module>()
      2 import pandas as pd
      3 import matplotlib.pyplot as plt
----> 4 import tensorflow as tf
      5 import cv2
      6 

ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by yasersakkaf** [comment]
I guess you don't have tensorflow in your machine
Please install tensorflow in your machine.
For that you can just go to the Anaconda Prompt which comes with anaconda already.
Just put the command `pip install tensorflow` and it will be installed.

**Comment by Breta01** [comment]
Yes, installing tensorflow should solve the problem. I will close this issue.
