### ISSUE TITLE
wordClass3 model (CTC) in OCR Evaluator is not working.

### ISSUE THREAD

**Issue by haripranavk** [Breta01/handwriting-ocr#43]
Hi Breta, while running OCR Evaluator, all the models are working except for worldClass3 model. 
Note :
as mentioned by you in a previous issue, I've changed the wordClass2 model to SeqRNN/Classifier.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-9169c609af50> in <module>()
     19            stats='CTC',
     20            slider=(60, 2),
---> 21            ctc=True)
     22 
     23 CharCycler(images,

<ipython-input-7-830c4c2a6808> in __init__(self, images, labels, charClass, stats, slider, ctc, seq2seq, charRNN)
     20         self.stats = stats
     21 
---> 22         self.evaluate()
     23 
     24     @abstractmethod

<ipython-input-7-830c4c2a6808> in evaluate(self)
     40         print()
     41         print("STATS:", self.stats)
---> 42         print(self.labels[1], ':', self.recogniseWord(self.images[1]))
     43         start_time = time.time()
     44         correctLetters = 0

<ipython-input-8-c3981b47644a> in recogniseWord(self, img)
     22             pred = self.charClass.eval_feed({'inputs:0': input_seq,
     23                                              'inputs_length:0': [length],
---> 24                                              'keep_prob:0': 1})[0]
     25 
     26             word = ''

~\Desktop\Ernst & Young\ICR\MIT\handwriting-ocr-master\ocr\tfhelpers.py in eval_feed(self, feed)
     30     def eval_feed(self, feed):
     31         """ Run the specified operation with given feed """
---> 32         return self.sess.run(self.op, feed_dict=feed)
     33 
     34     def run_op(self, op, feed, output=True):

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1114                              'which has shape %r' %
   1115                              (np_val.shape, subfeed_t.name,
-> 1116                               str(subfeed_t.get_shape())))
   1117           if not self.graph.is_feedable(subfeed_t):
   1118             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (135, 1, 120) for Tensor 'inputs:0', which has shape '(?, ?, 3600)'

**Comment by Breta01** [comment]
It is because of a wrong `slider` value, it should set as `slide=(60, 60)`. I will fix it in next commit.

**Comment by haripranavk** [comment]
Yes, it worked. Thank you!

**Comment by DHANOLA** [comment]
I am getting error 

![image](https://user-images.githubusercontent.com/55691616/197994026-74520d4b-3eab-4e8d-a517-f29ec3434985.png)


![image](https://user-images.githubusercontent.com/55691616/197994045-b3061843-fc37-4e5d-9cc4-58e6462a7665.png)
