### ISSUE TITLE
i couldn't quite understand how to use this

### ISSUE THREAD

**Issue by LogX7** [Breta01/handwriting-ocr#5]
hey, i'm building a platform for exam papers classifications using django ... 
and i need this to detect names of the students 
unfortunately, i couldn't quite understand how to use it since i don't have any experience in building ml models

i would appreciate it if you could explain the steps needed to send an image through your algorithm and get a response .. i really need this for a school project

**Comment by Breta01** [comment]
Hi,
First of all, this project focus on recognition of cursive handwriting and evaluation of different ML models.
In other to use these models you first have to get the images of words (names) from your papers. Then you have to standardize these images and feed them into the pre-trained ML model. To understand this process I would recommend to look on OCR-Evaluator.ipynb. I would recommend you to use the CTC model. For this model images are split into smaller slices which are than feed into the model. The model then outputs the sequence of letters.

One of the problems is that the current models are trained on my handwriting and you will probably need to find some better dataset for training and train the model on your own.

**Comment by yasersakkaf** [comment]
Hey LogX7, what happened?
Did the code work?
I think some models are missing from the directory.
If you have successfully executed the code then please share how you did it

**Comment by shantanuo** [comment]
Let's assume there are 100 employees in a company who will submit handwritten documents. Does it mean that I need to collect sample handwriting of all 100 individuals to train the model?

**Comment by Breta01** [comment]
The problem right now is that my training dataset is quite small (around 5k words). Therefore, the program won't work on handwriting of others. It would be the best solution to have samples from all 100 individuals to produce the best results, but I believe that if create a training dataset large enough, it will generalize for others' handwriting.

One of the main goals right now is to find an effective way of creating dataset and to create a dataset large as possible.
