### ISSUE TITLE
When Running CharClassifier getting 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Kiruba-Mediware** [Breta01/handwriting-ocr#52]
When I run CharClassifier , in step Load Images and Lables in CSV
I am getting 'NoneType' object is not subscriptable

**Comment by Kiruba-Mediware** [comment]
There is already an issue for this and also it has been closed , so no need this issue
https://github.com/Breta01/handwriting-ocr/issues/36

**Comment by Breta01** [comment]
Sorry, I still didn't have a time to fix the issue.

**Comment by Kiruba-Mediware** [comment]
Thanks @Breta01  for your immediate response. For now we used the fix mentioned in that case #36
