### ISSUE TITLE
To get accuracy in Final OCR.

### ISSUE THREAD

**Issue by yupmanojhere** [Breta01/handwriting-ocr#58]
Thanks Breta,
i increased train_steps and i also got 92% accuracy,But At Final,While Using That model in OCR word prediction is 70-75%.
I also Trained GapClassification with my dataset.
Still final accuracy in OCR is not upto 70%.
help me out Breta and Thanks for your hand to hand help.

**Comment by Breta01** [comment]
This issue is duplicate with #57 

Please do not make duplicate issue. I get notified every time when you comment under some issue, so there is no need to create new one. You should create new issues only when it is related to different problem.
