### ISSUE TITLE
How to sort the Indexes(Contours)? from Image left to right and top to bottom

### ISSUE THREAD

**Issue by Kiruba-Mediware** [Breta01/handwriting-ocr#59]
@Breta01  Currently the words are comes through the indexes in random format, 
How can we bring those words in correct order like " top-to-bottom-left-to-right", I have followed  this link
https://www.pyimagesearch.com/2015/04/20/sorting-contours-using-python-and-opencv/
But still I can't achieve completely, 
Any guidance can you please provide?

**Comment by sashankhrao** [comment]
I am new to python programming can you please help me with the code? and also help me to extract a document of handwritten text with indexes assigned.

**Comment by Breta01** [comment]
Hi, I still didn't write the solution for that. It shouldn't be that hard, just follow the steps described above. Right now I am working on a reorganization of this project, and I will be able to get to this problem in about a week. I am quite busy right now, so if you want some specific work from me, we can discuss it over email.

Also, can you explain a bit more what you mean by: handwritten text with **indexes assigned**?

**Comment by sashankhrao** [comment]
Hi @Breta01 
Is there any update on coding part for sorting the indexes?
Still I can't get rid out of it.

**Comment by Breta01** [comment]
You are lucky guy. I just finished it today. Currently it is only in `rework` branch under src/ocr/words.py you can find function `sort_words`. Also look into the `notebooks/OCR.ipynb` where is the whole process.

**Comment by sashankhrao** [comment]
Thank you so much for your response Breta. I was trying to run the first
cell of OCR.ipynb. I get this big error. Can you please help me fix this
issue? Thank you

Error:

Loading segmentation models...

---------------------------------------------------------------------------OSError
                                  Traceback (most recent call
last)<ipython-input-1-4f97e5c6ef9f> in <module>()      6 import cv2
  7 from ocr.normalization import word_normalization,
letter_normalization----> 8 from ocr import page, words, characters
  9 from ocr.helpers import implt, resize11     10 from ocr.tfhelpers
import Model
~\Documents\handwritten\ocr\characters.py in <module>()     14
location = os.path.dirname(os.path.abspath(__file__))     15 CNN_model
= Model(---> 16     os.path.join(location,
'../../models/gap-clas/CNN-CG'))     17 CNN_slider = (60, 30)     18
RNN_model = Model(
~\Documents\handwritten\ocr\tfhelpers.py in __init__(self, loc,
operation, input_name)     20         self.sess =
tf.Session(graph=self.graph)     21         with
self.graph.as_default():---> 22             saver =
tf.train.import_meta_graph(loc + '.meta', clear_devices=True)     23
          saver.restore(self.sess, loc)     24             self.op =
self.graph.get_operation_by_name(operation).outputs[0]
~\Anaconda3\envs\haroonenv\lib\site-packages\tensorflow\python\training\saver.py
in import_meta_graph(meta_graph_or_file, clear_devices, import_scope,
**kwargs)   1672   """  # pylint: disable=g-doc-exception   1673
return _import_meta_graph_with_return_elements(-> 1674
meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]   1675
 1676
~\Anaconda3\envs\haroonenv\lib\site-packages\tensorflow\python\training\saver.py
in _import_meta_graph_with_return_elements(meta_graph_or_file,
clear_devices, import_scope, return_elements, **kwargs)   1684
               "execution is enabled.")   1685   if not
isinstance(meta_graph_or_file, meta_graph_pb2.MetaGraphDef):-> 1686
 meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
 1687   else:   1688     meta_graph_def = meta_graph_or_file
~\Anaconda3\envs\haroonenv\lib\site-packages\tensorflow\python\framework\meta_graph.py
in read_meta_graph_file(filename)    631   meta_graph_def =
meta_graph_pb2.MetaGraphDef()    632   if not
file_io.file_exists(filename):--> 633     raise IOError("File %s does
not exist." % filename)    634   # First try to read it as a binary
file.    635   file_content = file_io.FileIO(filename, "rb").read()
OSError: File C:\Users\AI1_User1\Documents\handwritten\ocr\../../models/gap-clas/CNN-CG.meta
does not exist.

**Comment by Breta01** [comment]
First you have to download the models into `models/` folder (follow the instruction provided in the folder).  If you already done that, you have to switch to `rework` branch (you may have to pull the latest changes first).
