### ISSUE TITLE
Error while running the OCR.ipynb

### ISSUE THREAD

**Issue by Ali-H-Vahid** [Breta01/handwriting-ocr#6]
When I am running the first cell of file, I am facing with this error while I have cloned the repo using git LFS

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-fd9caaa4c04f> in <module>()
     11 # Import costume functions, corresponding to notebooks
     12 from ocr.normalization import imageNorm, letterNorm
---> 13 from ocr import page, words, charSeg
     14 from ocr.helpers import implt, resize
     15 from ocr.tfhelpers import Graph

~\handwriting-ocr\ocr\charSeg.py in <module>()
     11 print("Loading Segmantation model:")
     12 segCNNGraph = Graph('models/gap-clas/CNN-CG')
---> 13 segRNNGraph = Graph('models/gap-clas/RNN/Bi-RNN-new', 'prediction')
     14 
     15 def classify(img, step=2, RNN=False):

~\handwriting-ocr\ocr\tfhelpers.py in __init__(self, loc, operation, input_name)
     20         self.sess = tf.Session(graph=self.graph)
     21         with self.graph.as_default():
---> 22             saver = tf.train.import_meta_graph(loc + '.meta', clear_devices=True)
     23             saver.restore(self.sess, loc)
     24             self.op = self.graph.get_operation_by_name(operation).outputs[0]

c:\users\ali.vahid\appdata\local\continuum\anaconda3\envs\hwr\lib\site-packages\tensorflow\python\training\saver.py in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1684                                       clear_devices=clear_devices,
   1685                                       import_scope=import_scope,
-> 1686                                       **kwargs)
   1687   if meta_graph_def.HasField("saver_def"):
   1688     return Saver(saver_def=meta_graph_def.saver_def, name=import_scope)

c:\users\ali.vahid\appdata\local\continuum\anaconda3\envs\hwr\lib\site-packages\tensorflow\python\framework\meta_graph.py in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    502     importer.import_graph_def(
    503         input_graph_def, name=(import_scope or ""), input_map=input_map,
--> 504         producer_op_list=producer_op_list)
    505 
    506     scope_to_prepend_to_names = "/".join(

c:\users\ali.vahid\appdata\local\continuum\anaconda3\envs\hwr\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    281       # Set any default attr values that aren't present.
    282       if node.op not in op_dict:
--> 283         raise ValueError('No op named %s in defined operations.' % node.op)
    284       op_def = op_dict[node.op]
    285       for attr_def in op_def.attr:

ValueError: No op named StackV2 in defined operations.

**Comment by Breta01** [comment]
Hi,
This looks like compatibility issue. Can you tell me what version of TensorFlow do you have?
I think that the code should work for TensorFlow 1.3+
