### ISSUE TITLE
To append a Trained Model

### ISSUE THREAD

**Issue by yupmanojhere** [Breta01/handwriting-ocr#61]
Good Morning Breta,
Thanks for your Support.
I have a doubt in model training.
Is there any Possibility of Appending a Trained Model ?
The real issue is If i train a model with a single image,and while I'm training the next image with the model, it get overwritten but my idea is i want to append my model with every image i train.

Thanks Breta.

**Comment by Breta01** [comment]
Hi,
I am not really sure what you mean by your question. If I understand it correctly, you want to continue training of the model after already training the model. Best option is obviously to create one big dataset and train model on it rather then training it part by part. But if you really want to continue training some model, you can. Just load it as if you want to use model in production, but run the `train_step` operation instead.

**Comment by yupmanojhere** [comment]
Thanks breta it was helpfull!
