### ISSUE TITLE
I work on 64 bit :Is there any other way to extract the data or atleast can i get the idea (sample image) of raw data that the folder should have so i can download explicitly. It would be great if i can get some guidance 

### ISSUE THREAD

**Issue by Aditichintamani** [Breta01/handwriting-ocr#75]

**Comment by Breta01** [comment]
Can you better specify the problem? If you are working on 64bit architecture there shoudn't be any problem with the code. Or what exactly do you mean by 64 bit?

**Comment by Aditichintamani** [comment]
Hello Breta, Thank you so much for the responding i could accomplish the task successfully!
