### ISSUE TITLE
Error:while executing ocr_evaluator.ipynb

### ISSUE THREAD

**Issue by yhgupta** [Breta01/handwriting-ocr#77]
getting error 
OSError: File models/char-clas/en/CharClassifier.meta does not exist.

while executing
charClass_1 = Model('models/char-clas/' + LANG + '/CharClassifier')

wordClass = Model('models/word-clas/' + LANG + '/WordClassifier2', 'prediction_infer')
wordClass2 = Model('models/word-clas/' + LANG + '/SeqRNN/Classifier', 'word_prediction') # None
wordClass3 = Model('models/word-clas/' + LANG + '/CTC/Classifier2', 'word_prediction')

though all the files are in their proper folder

**Comment by Breta01** [comment]
My mistake the path is incorrect, I will update it as soon as possible. It should be:
`../models`
For example:
`'../models/char-clas/' + LANG + '/CharClassifier'`
