### ISSUE TITLE
Page detection issue

### ISSUE THREAD

**Issue by Austinn15** [Breta01/handwriting-ocr#81]
Hi,

Thanks for the help you have given for training smaller dimensional images. Here are some images where I couldn't able to find the page. Could you please tell me how your code works and what are the changes I have to make for detecting every single images like this? 
Note: These images are captured with mobile without flash and with flash.But no result in detecting the page.
Please help. 
![20190301_145315](https://user-images.githubusercontent.com/39292734/53882357-25ecc480-403c-11e9-8d0e-b77924855eda.jpg)
![croptest](https://user-images.githubusercontent.com/39292734/53882358-25ecc480-403c-11e9-96dc-f4c88adc9825.jpg)
![img_20190304_124214](https://user-images.githubusercontent.com/39292734/53882360-26855b00-403c-11e9-9eac-6d62552d231a.jpg)

**Comment by Breta01** [comment]
Hi,
you should look into [page_detection.ipynb](https://github.com/Breta01/handwriting-ocr/blob/master/notebooks/page_detection.ipynb). There is the whole process. First I would recommend making better pictures. You should try to cover most of the photo with the page and trying to have good contrast between background and paper. The whole process of detection is described here: [https://bretahajek.com/2017/01/scanning-documents-photos-opencv/](https://bretahajek.com/2017/01/scanning-documents-photos-opencv/)

**Comment by Austinn15** [comment]
Thank you so much for the information.
