### ISSUE TITLE
Unable to extract data

### ISSUE THREAD

**Issue by guest44332** [Breta01/handwriting-ocr#82]
Is there any way to extract the data without enchant? I am using a 64 bit computer and is unable to install enchant at all.

**Comment by Breta01** [comment]
I see that the enchant project is no longer maintained. I will replace it as soon as possible.

**Comment by guest44332** [comment]
Thank you. Is it possible to train the model using the raw images? I am trying to train the model for handwritten numbers. May I also know which model should I use for that?

**Comment by Breta01** [comment]
You can train using raw images, but you still have to do some preprocessing (for example normalize the height). Also other types of preprocessing can improve the accuracy. For number recognition, I would recommend ORAND dataset, but it seems to be down. You can also try MNIST or NIST dataset and construct artificial images from single character images. Or just recognise the characters one by one.

**Comment by Breta01** [comment]
I replaced the `enchant` with module with simple `unidecode` that means that there might be some non-english words with removed accents. I think it should affect the accuracy of resulting models.
