### ISSUE TITLE
ORAND CAR 2014 dataset site is down. How to download it?

### ISSUE THREAD

**Issue by shubham1305** [Breta01/handwriting-ocr#83]

**Comment by Breta01** [comment]
Thanks for the information. There's not much I can do. You should try looking, if it is stored somewhere else.

Please let me know if you find a new link

**Comment by Breta01** [comment]
Here is the thing. You can still find the dataset stored on their site. However since they took down the page with all the information and licensing, I won't be sharing it here. But the wayback machine can do the trick :wink:
