### ISSUE TITLE
Error in OCR.ipynb (name 'resize' is not defined)

### ISSUE THREAD

**Issue by ArunReddyAIedge** [Breta01/handwriting-ocr#89]
##Please help me with this error. I am just trying to run the model and i encountered this error.
I tried few things but none of them worked.

NameError                                 Traceback (most recent call last)
<ipython-input-7-bf1b9dbe4960> in <module>
      1 # Crop image and get bounding boxes
----> 2 crop = page.detection(image)
      3 implt(crop)
      4 boxes = words.detection(crop)
      5 lines = words.sort_words(boxes)

E:\handwriting-ocr-master\handwriting-ocr-master\src\ocr\page.py in detection(image)
     11     """Finding Page."""
     12     # Edge detection
---> 13     image_edges = _edges_detection(image, 200, 250)
     14 
     15     # Close gaps between edges (double page clouse => rectangle kernel)

E:\handwriting-ocr-master\handwriting-ocr-master\src\ocr\page.py in _edges_detection(img, minVal, maxVal)
     28 def _edges_detection(img, minVal, maxVal):
     29     """Preprocessing (gray, thresh, filter, border) + Canny edge detection."""
---> 30     img = cv2.cvtColor(cv2.resize(img), cv2.COLOR_BGR2GRAY)
     31 
     32     img = cv2.bilateralFilter(img, 9, 75, 75)

NameError: name 'resize' is not defined

**Comment by Breta01** [comment]
Looks like you made some changes to the file, there should be only:
```Python
img = cv2.cvtColor(resize(img), cv2.COLOR_BGR2GRAY)
```

**Comment by ArunReddyAIedge** [comment]
yes sir, I did make some changes. But that was assuming that it resize is a open c argument. But turns out it is no and I changed it back but still it doesn't work, Please help me with it.

**Comment by Breta01** [comment]
And what error it shows now? The resize function is defined in `helpers.py` as:
```Python
def resize(img, height=SMALL_HEIGHT, allways=False):
    """Resize image to given height."""
    if (img.shape[0] > height or allways):
        rat = height / img.shape[0]
        return cv2.resize(img, (int(rat * img.shape[1]), height))
    
return img
```
It should be imported by line:
```Python
from .helpers import *
```

**Comment by ArunReddyAIedge** [comment]
It seems like the error is with the function _persp_transform.
Unfortunately I couldn't find where it is defined. 

OverflowError                             Traceback (most recent call last)
<ipython-input-4-1c98ef642184> in <module>
      1 # Crop image and get bounding boxes of words
----> 2 crop = page.detection(image)
      3 implt(crop)
      4 bBoxes = words.detection(crop)

E:\handwriting-ocr-master\handwriting-ocr-master\src\ocr\page.py in detection(image)
     22     page_contour = page_contour.dot(np.size(image))
     23     # Transform prespective
---> 24     new_image = _persp_transform(image, page_contour)
     25     new_image = np.asarray(new_array, dtype=None, order=None)
     26     return new_image

E:\handwriting-ocr-master\handwriting-ocr-master\src\ocr\page.py in _persp_transform(img, s_points)
    117     M = np.asarray(M,dtype=None, order=None)
    118     img = np.asarray(img, dtype=None, order=None)
--> 119     return cv2.warpPerspective(img, M, (int(width), int(height)))

OverflowError: Python int too large to convert to C long  

P.S please don't get frustrated by seeing my doubts

**Comment by Breta01** [comment]
You can find where it is defined from the log: `src\ocr\page.py`. This seems like the width or height number is wrong. But I am not really sure what causing this issue. I have never seen it before.
