### ISSUE TITLE
Where is the CTC classifier for english?

### ISSUE THREAD

**Issue by yasersakkaf** [Breta01/handwriting-ocr#9]
Hello Breta,

Nice work on the OCR.
How ever I couldn't find the models/word-clas/en/CTC/Classifier2 model.
Please provide it.

**Comment by Breta01** [comment]
Hi,

I am sorry for the inconvenience. I had some issues with GitHub LFS. Right now you can download all the models from here (download them and unzip them in models directory):

[https://drive.google.com/file/d/1YbmsiJK3Wclfm6K8PrJuz-QROEKX1qis/view?usp=sharing](https://drive.google.com/file/d/1YbmsiJK3Wclfm6K8PrJuz-QROEKX1qis/view?usp=sharing)

Hope it helps.

**Comment by yasersakkaf** [comment]
Thank you so much man.
I wish to meet you some day.
